version: '3.9'

x-default: &default
  build: .
  volumes:
    - .:/var/www/e-ticketing-system-api
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: postgres
    REDIS_URL: redis://redis:6379/0

services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:4.0-alpine

  web:
    <<: *default
    command: >
      sh -c "
        rm -rf tmp/pids/server.pid \
        & bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  sidekiq:
    <<: *default
    command: bundle exec sidekiq -c 2
    depends_on:
      - redis

volumes:
  postgres-data:
