default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_ticketing_system_api_development
  username: <%= ENV.fetch("POSTGRES_USER") { $USER } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

test:
  <<: *default
  database: e_ticketing_system_api_test
  username: <%= ENV.fetch("POSTGRES_USER") { $USER } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

production:
  <<: *default
  database: e_ticketing_system_api_production
  username: e_ticketing_system
  password: <%= ENV['E_TICKETING_SYSTEM_API_PASSWORD'] %>
